// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: weather.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WeatherServiceClient is the client API for WeatherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WeatherServiceClient interface {
	// rpc GetWeatherStream(GetWeatherRequest) returns (stream GetWeatherResponse) {}
	GetWeatherData(ctx context.Context, in *RequestWeatherData, opts ...grpc.CallOption) (*ResponseWeatherData, error)
	GetUserCity(ctx context.Context, in *RequstUserCity, opts ...grpc.CallOption) (*ResponseUserCity, error)
}

type weatherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWeatherServiceClient(cc grpc.ClientConnInterface) WeatherServiceClient {
	return &weatherServiceClient{cc}
}

func (c *weatherServiceClient) GetWeatherData(ctx context.Context, in *RequestWeatherData, opts ...grpc.CallOption) (*ResponseWeatherData, error) {
	out := new(ResponseWeatherData)
	err := c.cc.Invoke(ctx, "/weather.WeatherService/GetWeatherData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weatherServiceClient) GetUserCity(ctx context.Context, in *RequstUserCity, opts ...grpc.CallOption) (*ResponseUserCity, error) {
	out := new(ResponseUserCity)
	err := c.cc.Invoke(ctx, "/weather.WeatherService/GetUserCity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeatherServiceServer is the server API for WeatherService service.
// All implementations must embed UnimplementedWeatherServiceServer
// for forward compatibility
type WeatherServiceServer interface {
	// rpc GetWeatherStream(GetWeatherRequest) returns (stream GetWeatherResponse) {}
	GetWeatherData(context.Context, *RequestWeatherData) (*ResponseWeatherData, error)
	GetUserCity(context.Context, *RequstUserCity) (*ResponseUserCity, error)
	mustEmbedUnimplementedWeatherServiceServer()
}

// UnimplementedWeatherServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWeatherServiceServer struct {
}

func (UnimplementedWeatherServiceServer) GetWeatherData(context.Context, *RequestWeatherData) (*ResponseWeatherData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWeatherData not implemented")
}
func (UnimplementedWeatherServiceServer) GetUserCity(context.Context, *RequstUserCity) (*ResponseUserCity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserCity not implemented")
}
func (UnimplementedWeatherServiceServer) mustEmbedUnimplementedWeatherServiceServer() {}

// UnsafeWeatherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeatherServiceServer will
// result in compilation errors.
type UnsafeWeatherServiceServer interface {
	mustEmbedUnimplementedWeatherServiceServer()
}

func RegisterWeatherServiceServer(s grpc.ServiceRegistrar, srv WeatherServiceServer) {
	s.RegisterService(&WeatherService_ServiceDesc, srv)
}

func _WeatherService_GetWeatherData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestWeatherData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherServiceServer).GetWeatherData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/weather.WeatherService/GetWeatherData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherServiceServer).GetWeatherData(ctx, req.(*RequestWeatherData))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeatherService_GetUserCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequstUserCity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherServiceServer).GetUserCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/weather.WeatherService/GetUserCity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherServiceServer).GetUserCity(ctx, req.(*RequstUserCity))
	}
	return interceptor(ctx, in, info, handler)
}

// WeatherService_ServiceDesc is the grpc.ServiceDesc for WeatherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WeatherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weather.WeatherService",
	HandlerType: (*WeatherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWeatherData",
			Handler:    _WeatherService_GetWeatherData_Handler,
		},
		{
			MethodName: "GetUserCity",
			Handler:    _WeatherService_GetUserCity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "weather.proto",
}
